/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as ApiPublicPostImageSplatRouteImport } from './routes/api/public/post-image/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostImageSplatRoute = ApiPublicPostImageSplatRouteImport.update({
  id: '/api/public/post-image/$',
  path: '/api/public/post-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/public/post-image/$': typeof ApiPublicPostImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/public/post-image/$': typeof ApiPublicPostImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/public/post-image/$': typeof ApiPublicPostImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/posts/$id' | '/api/public/post-image/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/posts/$id' | '/api/public/post-image/$'
  id: '__root__' | '/' | '/explore' | '/posts/$id' | '/api/public/post-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  PostsIdRoute: typeof PostsIdRoute
  ApiPublicPostImageSplatRoute: typeof ApiPublicPostImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-image/$': {
      id: '/api/public/post-image/$'
      path: '/api/public/post-image/$'
      fullPath: '/api/public/post-image/$'
      preLoaderRoute: typeof ApiPublicPostImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  PostsIdRoute: PostsIdRoute,
  ApiPublicPostImageSplatRoute: ApiPublicPostImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
